# Provide API access to the engine pod
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole 
metadata:
  name: {{ .Values.deployment.name }}-controller
  labels:
    app: {{ .Values.engine.labels.app }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "services"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "create", "delete"]
