apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata:
  name: {{ .Values.deployment.name }}-controller
  labels:
    app: {{ .Values.engine.labels.app }}
subjects:
  - kind: ServiceAccount
    name: {{.Values.deployment.name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.deployment.name }}-controller
  apiGroup: rbac.authorization.k8s.io

