apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: me-logs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.logs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: me-repo-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.repo.size }}
