# Expose the engine (grpc and UI) as a service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.engine.labels.app }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    name: grpc-port
    protocol: TCP
    targetPort: {{ .Values.engine.grpcPort }}
  - port: {{ .Values.service.uiPort }}
    name: ui-port
    protocol: TCP
    targetPort: {{ .Values.engine.uiPort }}
  selector:
    app: {{ .Values.engine.labels.app }}
