[build-system]
requires = ["setuptools>=40.8.0", "wheel", "setuptools_scm"]

[tool.black]
line-length = 111
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | buck-out
  | build
  | cache
  | dist
  | notebooks
  | _stubs
)/
'''
